var hasla=new Array(100);
var kategoria=new Array(100);
hasla[0]="Tchórze giną w chańbie";			kategoria[0]="Powiedzenie z gry Dawn of War";
hasla[1]="Latający potwór spaghetti";		kategoria[1]="Bóg, który nie jest brany na poważnie";
hasla[2]="Syzyfowa praca";						kategoria[2]="Inaczej bezowocna praca";
hasla[3]="Statek matka";							kategoria[3]="Fantastyka naukowa";
hasla[4]="Domokrążca";							kategoria[4]="Postać";
hasla[5]="Jednorożec";							kategoria[5]="Magiczne stworzenia";
hasla[6]="Tyle co kot napłakał";				kategoria[6]="Przysłowia";
hasla[7]="Jak grochem o ściane";				kategoria[7]="Przysłowia";
hasla[8]="Mercedes";								kategoria[8]="Samochody";
hasla[9]="Lamborghini";							kategoria[9]="Samochody";
hasla[10]="Antysemityzm";						kategoria[10]="Poglądy";
hasla[11]="Antyterrorysta";						kategoria[11]="Zawód";
hasla[12]="Tyranozaur";							kategoria[12]="Prehistoria";
hasla[13]="Counter Strike";						kategoria[13]="Gry komputerowe";
hasla[14]="Prototyp";								kategoria[14]="Rzeczownik";
hasla[15]="Biedronka";							kategoria[15]="Zwierzęta";
hasla[16]="Bez pracy nie ma kołaczy";		kategoria[16]="Przysłowia";
hasla[17]="Enigmatyczny";						kategoria[17]="Przymiotnik";
hasla[18]="Lekkoatletyka";						kategoria[18]="Dziedzina sportowa";
hasla[19]="Interpunkcja";						kategoria[19]="Gramatyka";
hasla[20]="Telekomunikacja";					kategoria[20]="Sieci";
hasla[21]="Metamorfoza";						kategoria[21]="Inaczej przemiana";
hasla[22]="Zwierzchnictwo";					kategoria[22]="Rzeczownik";
hasla[23]="Prześladowanie";					kategoria[23]="Rzeczownik";
hasla[24]="Dźwiękonaśladownictwo";		kategoria[24]="Rzeczownik";
hasla[25]="Antykoncepcja";						kategoria[25]="Zabezpieczenia";
hasla[26]="Kolorowanka";						kategoria[26]="Rzeczownik";
hasla[27]="Luminescencja";						kategoria[27]="Rzeczownik";
hasla[28]="Adwokat diabła";					kategoria[28]="Filmy";
hasla[29]="Diabeł ubiera się u prady";		kategoria[29]="Filmy";
hasla[30]="Windst of Plague";					kategoria[30]="Zespoły muzyczne";
hasla[31]="Breakdown of sanity";			kategoria[31]="Zespoły muzyczne";
hasla[32]="Lucyfer";								kategoria[32]="Postać";
hasla[33]="Samael";								kategoria[33]="Postać";
hasla[34]="Behemoth";							kategoria[34]="Polskie zespoły muzyczne";
hasla[35]="Frontside";								kategoria[35]="Polskie zespoły muzyczne";
hasla[36]="Heaven shall burn";					kategoria[36]="Zespoły muzyczne";
hasla[37]="Gandalf";								kategoria[37]="Postać";
hasla[38]="Frodo Baggins";						kategoria[38]="Główny bohater";
hasla[39]="Harry Potter";							kategoria[39]="Główny bohater";
hasla[40]="Richard Riddick";						kategoria[40]="Główny bohater";
hasla[41]="Mizantropia";							kategoria[41]="Poglądy";
hasla[42]="Chuj w dupe policji";				kategoria[42]="Przysłowia";
hasla[43]="Kolorowe serca";					kategoria[43]="Rzeczownik";
hasla[44]="Ortodoksyjny";						kategoria[44]="Przymiotnik";
hasla[45]="Dotkliwy dotyk";						kategoria[45]="Rzeczownik";
hasla[46]="Satanizm";								kategoria[46]="Wierzenia i przesądy";
hasla[47]="Klaustrofobia";						kategoria[47]="Lęki";
hasla[48]="Ksenofobia";							kategoria[48]="Lęki";
hasla[49]="Lęk wysokości";						kategoria[49]="Lęki";
hasla[50]="Konkatenacja";						kategoria[50]="Programowanie";
hasla[51]="Inkrementacja";						kategoria[51]="Programowanie";
hasla[52]="Dekrementacja";					kategoria[52]="Programowanie";
hasla[53]="Rekurencja";							kategoria[53]="Matematyka";
hasla[54]="Funkcja kwadratowa";			kategoria[54]="Matematyka";
hasla[55]="Funkcja liniowa";					kategoria[55]="Matematyka";
hasla[56]="Polimorfia";							kategoria[56]="Umiejętności z świata fantasy";
hasla[57]="Lewitacja";								kategoria[57]="Umiejętności z świata fantasy";
hasla[58]="Telekineza";							kategoria[58]="Umiejętności z świata fantasy";
hasla[59]="Wampir";								kategoria[59]="Magiczne stworzenia";
hasla[60]="Wilkołak";								kategoria[60]="Magiczne stworzenia";
hasla[61]="Elf leśny";								kategoria[61]="Magiczne stworzenia";
hasla[62]="Kamienny golem";					kategoria[62]="Magiczne stworzenia";
hasla[63]="Tablica asocjacyjna";				kategoria[63]="Programowanie";
hasla[64]="Within the ruins";					kategoria[64]="Zespoły muzyczne";
hasla[65]="Slayer";									kategoria[65]="Zespoły muzyczne";
hasla[66]="Ensiferum";							kategoria[66]="Zespoły muzyczne";
hasla[67]="Hard rock";							kategoria[67]="Gatunki muzyczne";
hasla[68]="Death metal";							kategoria[68]="Gatunki muzyczne";
hasla[69]="Dubstep";								kategoria[69]="Gatunki muzyczne";
hasla[70]="Metalstep";								kategoria[70]="Gatunki muzyczne";
hasla[71]="Hardstyle";								kategoria[71]="Gatunki muzyczne";
hasla[72]="Deathcore";							kategoria[72]="Gatunki muzyczne";
hasla[73]="Metalcore";							kategoria[73]="Gatunki muzyczne";
hasla[74]="Paladyn";								kategoria[74]="Klasy postaci z gier";
hasla[75]="Czarodziej";							kategoria[75]="Klasy postaci z gier";
hasla[76]="Łotrzyk";								kategoria[76]="Klasy postaci z gier";
hasla[77]="Death note";							kategoria[77]="Anime";
hasla[78]="Fairy tail";								kategoria[78]="Anime";
hasla[79]="Ichigo Kurosaki";					kategoria[79]="Główny bohater";
hasla[80]="Uzumaki Naruto";					kategoria[80]="Główny bohater";
hasla[81]="Bleach";									kategoria[81]="Anime";
hasla[82]="Higurashi no naku koro ni";		kategoria[82]="Anime";
hasla[83]="Piła łańcuchowa";					kategoria[83]="Narzędzia";
hasla[84]="Krajzega";								kategoria[84]="Narzędzia";
hasla[85]="Młot udarowy";						kategoria[85]="Narzędzia";
hasla[86]="Halabarda";							kategoria[86]="Broń średniowieczna";
hasla[87]="Morgensztern";						kategoria[87]="Broń średniowieczna";
hasla[88]="Korbacz";								kategoria[88]="Broń średniowieczna";
hasla[89]="Flamberg";								kategoria[89]="Broń średniowieczna";
hasla[89]="Trebusz";								kategoria[89]="Broń średniowieczna";
hasla[90]="Balista";									kategoria[90]="Broń średniowieczna";
hasla[91]="Wyspecjalizowany";				kategoria[91]="Przymiotnik";
hasla[92]="Hermiona Granger";				kategoria[92]="Postać";
hasla[93]="Ronald Weasley";					kategoria[93]="Postać";
hasla[94]="Lord Voldemort";					kategoria[94]="Czarny charakter";
hasla[95]="Darth Vader";							kategoria[95]="Czarny charakter";
hasla[96]="Sauron";								kategoria[96]="Czarny charakter";
hasla[97]="Hedonizm";							kategoria[97]="Poglądy";
hasla[98]="Konsumpcjonizm";					kategoria[98]="Poglądy";
hasla[99]="Anhedonia";							kategoria[99]="Poglądy";